export const YIELD_DUEL_LOG_ABI = [
  {
    type: "function",
    name: "commitDuel",
    stateMutability: "nonpayable",
    inputs: [
      { name: "humanUsdy", type: "uint8" },
      { name: "humanMeth", type: "uint8" },
      { name: "humanMnt", type: "uint8" },
      { name: "agentUsdy", type: "uint8" },
      { name: "agentMeth", type: "uint8" },
      { name: "agentMnt", type: "uint8" },
      { name: "humanYieldBps", type: "uint16" },
      { name: "agentYieldBps", type: "uint16" },
      { name: "humanReasoningHash", type: "bytes32" },
      { name: "agentReasoningHash", type: "bytes32" },
    ],
    outputs: [{ name: "duelId", type: "bytes32" }],
  },
  {
    type: "function",
    name: "logDecision",
    stateMutability: "nonpayable",
    inputs: [
      { name: "actor", type: "uint8" },
      { name: "usdyPct", type: "uint8" },
      { name: "methPct", type: "uint8" },
      { name: "mntPct", type: "uint8" },
      { name: "reasoningHash", type: "bytes32" },
    ],
    outputs: [{ name: "decisionId", type: "uint256" }],
  },
  {
    type: "function",
    name: "triggerAgentInference",
    stateMutability: "nonpayable",
    inputs: [{ name: "inferenceHash", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "decisionCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "duelCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "event",
    name: "DuelCommitted",
    inputs: [
      { name: "duelId", type: "bytes32", indexed: true },
      { name: "duelist", type: "address", indexed: true },
      { name: "humanYieldBps", type: "uint16", indexed: false },
      { name: "agentYieldBps", type: "uint16", indexed: false },
      { name: "winner", type: "uint8", indexed: false },
    ],
  },
] as const;